### PR TITLE
fixing buggies

### PR DESCRIPTION
**Pull request by LinguList**

### CODE REVIEW

**Comment by xrotwang** [comment]
@LinguList it seems a sound used in the tests was added. Can you run the test suite locally?

**Comment by LinguList** [comment]
will do soon...

**Comment by LinguList** [comment]
somehow, my pyteset doesn't work... it says: 

```
usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --cov
  inifile: /home/jmlist/projects/scripts/clts/setup.cfg
  rootdir: /home/jmlist/projects/scripts/clts
```

**Comment by xrotwang** [comment]
did you run `pip install -r requirements.txt`? This should install `coverage`, too, which provides support for the `--cov` option.

**Comment by LinguList** [comment]
Okay, all my errors. This happens if you don't work on a project for half a year or so. I hope the current update finally fixes this, soo that "ä" is now accepted as valid sound in clts.

**Comment by xrotwang** [comment]
yep, looks good. feel free to merge.

**Comment by LinguList** [comment]
Okay, but good that the test suite is so consistent that it's not taking too long of a time to spot the problems. If @tresoldi makes the next major changes with @cormacanderson, it'll be a lot that awaits us, but it seems to still work robustly enough, so we can prepare next week's release...

**Pull request merged**
